### ISSUE TITLE
.so files built now throws error `ValueError: Incompatible Language version 12. Must not be between 9 and 11`

### ISSUE THREAD

**Issue by rcshubhadeep** [tree-sitter/py-tree-sitter#38]
I just built a .so file for Python language (using py-tree-sitter) and now then I am trying to use it, it throws an error - 

`ValueError: Incompatible Language version 12. Must not be between 9 and 11`

**Comment by rcshubhadeep** [comment]
👍

**Comment by rcshubhadeep** [comment]
I am not sure what I am missing here but I am going to write exact steps I did

1.> Created a fresh `virtualenv` with `Python 3.6.5`

2.> installed tree_sitter and ipython in it. Like so - `pip3 install --no-cache-dir tree_sitter`

3.> Created a directory called `vendor`

4.> `cd` into `vendor` and did `git clone https://github.com/tree-sitter/tree-sitter-go` and `git clone https://github.com/tree-sitter/tree-sitter-python`

5.> Opened the ipython prompt

6.> Did exactly the following steps

```
In [1]: rm -f my-languages.so

In [2]: from tree_sitter import Language, Parser

In [3]: Language.build_library(
   ...:   # Store the library in the `build` directory
   ...:   'my-languages.so',
   ...:
   ...:   # Include one or more languages
   ...:   [
   ...:     'vendor/tree-sitter-go',
            'vendor/tree-sitter-python'
   ...:   ]
   ...: )
Out[3]: True

In [4]: parser = Parser()

In [5]: GO_LANGUAGE = Language('my-languages.so', 'go')

In [6]: parser.set_language(GO_LANGUAGE)
```

7.> At this point it throws me this error (irrespective whether I am trying to use `PY_LANGUAGE` or `GO_LANGUAGE` )

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-0310ba5ce61d> in <module>
----> 1 parser.set_language(GO_LANGUAGE)

ValueError: Incompatible Language version 12. Must not be between 9 and 11
```

What am I missing? What shall I do?

Please help.

Thanks in advance.

**Comment by maxbrunsfeld** [comment]
This is an incompatibility between the latest version of `tree-sitter-python` and the older version of `tree-sitter` that this library was using. I have published a new version, [`0.2.0`](https://pypi.org/project/tree-sitter/0.2.0), that should fix this.

**Comment by mumar-cybershell** [comment]
I am using tree-sitter-python and tree-sitter-c with 0.2.0, 0.2.1, 0.2.2. Having the same issue 
`ValueError: Incompatible Language version 13. Must not be between 9 and 12`

**Comment by gkoumasd** [comment]
> I am using tree-sitter-python and tree-sitter-c with 0.2.0, 0.2.1, 0.2.2. Having the same issue
> `ValueError: Incompatible Language version 13. Must not be between 9 and 12`

Hi I am experiencing the same issue, the new version, 0.2.0 does not solve the issue. Any suggestion?

**Comment by lunixbochs** [comment]
Reopening - I assume this needs a tree-sitter core submodule version bump. You might be able to do this yourself locally by updating the core/ submodule.

**Comment by gkoumasd** [comment]
> Reopening - I assume this needs a tree-sitter core submodule version bump. You might be able to do this yourself locally by updating the core/ submodule.

Thanks for the feedback! How can I update the core/submodule?

**Comment by gkoumasd** [comment]
> tree-sitter core submodule version bump

Thank you for the feedback!
I've tried the new version, i.e., 0.2.2 but I still get the same error. How can I update the core/submodule?

**Comment by Symbolk** [comment]
Same issue for the 0.2.1 installed via `pip install tree_sitter`:
![image](https://user-images.githubusercontent.com/14107297/142364317-4e2d167c-876d-47cb-8534-4974544d8f87.png)


![image](https://user-images.githubusercontent.com/14107297/142364311-84479e26-eea5-4f25-8d2d-606a4e862286.png)

**Comment by maxbrunsfeld** [comment]
FYI, I published [`tree_sitter` 0.20](https://pypi.org/project/tree-sitter/) to PyPi. Closing this out because I think  it was answered.

**Comment by nandishaivalli** [comment]
I was facing the same issue, 
ValueError: Incompatible Language version 11. Must be between 13 and 14. 

I used different **my-languages.so** file from [here](https://github.com/microsoft/CodeBERT/tree/master/GraphCodeBERT/codesearch/parser) 
It helped to solve my issue.

**Comment by madebr** [comment]
Hello!

Installing the (current) latest packages as:
```cmd
python -m pip install tree-sitter==0.24.0 tree-sitter-c==0.23.5
```
and running the following snippet:
```python
import tree_sitter_c as tsc
from tree_sitter import Language, Parser

C_LANGUAGE = Language(tsc.language())
parser = Parser(C_LANGUAGE)
```
results in the following error:
```cmd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Incompatible Language version 15. Must be between 13 and 14
```

**Comment by FlorianSchwendinger** [comment]
> Hello!
> 
> Installing the (current) latest packages as:
> 
> python -m pip install tree-sitter==0.24.0 tree-sitter-c==0.23.5
> and running the following snippet:
> 
> import tree_sitter_c as tsc
> from tree_sitter import Language, Parser
> 
> C_LANGUAGE = Language(tsc.language())
> parser = Parser(C_LANGUAGE)
> results in the following error:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ValueError: Incompatible Language version 15. Must be between 13 and 14

using 

    python -m pip install tree-sitter-c==0.23.4

resolved the issue for me.

**Comment by tfachmann** [comment]
When are we expecting to get support for language version 15?
