### ISSUE TITLE
Possible memory leak when using captures

### ISSUE THREAD

**Issue by Kleinkop** [tree-sitter/py-tree-sitter#46]
I run py-tree-sitter on a Windows system in an almost clean 32bit 3.6 Python venv.
While parsing a LOT of files and running the same query on each of the resulting trees I found myself out of memory rather quickly. I tried to narrow down the source of my leak:

>     query = PY_LANG.query(""" some query string with captures"")
>     for root, _, files in os.walk("some/repos/"):
>         for fn in files:
>             if fn.endswith(".py"):
>                 with open(os.path.join(root, fn), mode="rb") as fd:
>                     tree = parser.parse(fd.read())
>                 query.captures(tree.root_node)

After playing around with the above code a little `query.captures(tree.root_node)` seems to be cause, since other tree operations or even just parsing are working perfectly fine. Other repositories using the python tree-sitter I know also don't really use queries , so I wondered whether this is known/intended behaviour and I'm just using it wronly or a genuine bug.
I tried looking at the C bindings, but unfortunately I'm quite inexperienced with C, so I couldn't find the exact cause.

**Comment by sogaiu** [comment]
Which version are you using?

I think I fixed some in https://github.com/tree-sitter/py-tree-sitter/pull/40 -- though it's possible there are still more.

**Comment by Kleinkop** [comment]
I originally used the 0.2.0 version via pip, but I just tried using the current master branch and the problem still occured.

**Comment by sogaiu** [comment]
Hmmm, nothing useful comes to mind immediately.

May be @maxbrunsfeld might have some ideas...

**Comment by maxbrunsfeld** [comment]
I think this is the same kind of leak that was fixed in #50. It looks like the `captures` method uses similar code for creating a tuple. I will fix it.

**Comment by maxbrunsfeld** [comment]
This is fixed in 0.2.2.
